import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'de' | 'en' | 'cat';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    analytics: 'Analytics',
    allianceFormTitle: 'Alliance Projects',
    fassungFormTitle: 'Fassung Projects',
    paveFormTitle: 'Pavé Projects',
    userManagement: 'Team',
    dashboardTitle: 'Atelier Overview',
    dashboardSubtitle: 'Workflow optimization and financial tracking.',
    totalProjects: 'Total Projects',
    in_progress: 'In Progress',
    completed: 'Completed',
    pending: 'Pending',
    weeklyWorkload: 'Team Workload',
    completedRevenue: 'Revenue',
    projectsInProgress: 'Active Projects',
    loading: 'Loading...',
    noProjects: 'No projects in this period.',
    createProject: 'Create Project',
    projectSaved: 'Project saved!',
    allProjects: 'All Projects',
    stoneSize: 'Stone Size (mm)',
    stoneType: 'Stone Type',
    material: 'Material',
    style: 'Style',
    shape: 'Shape',
    timePerStone: 'Time/Stone (min)',
    totalTime: 'Est. Total Time',
    actualTime: 'Actual Time',
    pricePerStone: 'Price/Stone (CHF)',
    goldBack: 'Gold Back (g)',
    client: 'Client',
    date: 'Start Date',
    deadline: 'Deadline',
    stoneCount: 'Stone Count',
    layout: 'Layout',
    fixation: 'Fixation',
    submit: 'Add to Schedule',
    extraHours: 'Extra Hours',
    addUser: 'Add User',
    newUser: 'New User Name',
    status: 'Status',
    projectName: 'Project Name',
    revenue: 'Revenue',
    basedOnCompleted: 'Based on selection',
    filter_week: 'Week',
    filter_month: 'Month',
    filter_year: 'Year',
    filter_all: 'All',
    editProject: 'Edit Project',
    agreedPrice: 'Agreed Price',
    priceAlert: 'Cost exceeds estimate',
    saveChanges: 'Save Changes',
    proposalSimulation: 'Proposal Simulation',
    difficultyMargin: 'Difficulty Margin',
    urgencyFee: 'Urgency Fee',
    suggestedPrice: 'Suggested Price',
    suggestedDate: 'Optimized Delivery',
    calculate: 'Simulate',
    assignedTo: 'Assigned To',
    filterByUser: 'Filter by Jeweler',
    allUsers: 'All Team',
    close: 'Close',
    previousMonth: 'Previous Month',
    nextMonth: 'Next Month',
    // Timer
    startTimer: 'Start Timer',
    stopTimer: 'Stop Timer',
    timerActive: 'Timer running',
    elapsedTime: 'Elapsed',
    estimatedCost: 'Est. Cost',
    profitMargin: 'Margin',
    // Analytics
    analyticsTitle: 'Analytics & Profitability',
    analyticsSubtitle: 'Financial performance and optimization recommendations.',
    revenueToday: 'Today',
    revenueMonth: 'This Month',
    revenueYear: 'This Year',
    revenueAllTime: 'All Time',
    profitabilityByType: 'Profitability by Type',
    topClients: 'Top Clients',
    monthlyTrend: 'Monthly Revenue Trend',
    chfPerHour: 'CHF/hour',
    recommendations: 'Recommendations',
    projectCount: 'Projects',
    avgPrice: 'Avg. Price',
    mostProfitable: 'Most profitable type',
    bestClient: 'Best client',
    hourlyRate: 'Avg. hourly rate',
    // User management
    workingDays: 'Working Days',
    daysOff: 'Days Off',
    addDayOff: 'Add day off',
    mon: 'Mon', tue: 'Tue', wed: 'Wed', thu: 'Thu', fri: 'Fri', sat: 'Sat', sun: 'Sun',
    availability: 'Availability',
    // Smart prediction
    smartPrediction: 'Smart Prediction',
    basedOnSimilar: 'Based on {count} similar projects',
    predictedTime: 'Predicted Time',
    predictedPrice: 'Predicted Price',
    timeRange: 'Range',
    goldPrice: 'Gold price',
    goldPriceLabel: 'Gold (CHF/g)',
    overdueToday: 'Overdue/Today',
    daysLabel: 'days',
    ofEstimated: 'of {est} est.',
    recBestType: '{type} ({rate} CHF/h). Prioritize it to maximize profit.',
    recBestClient: '{client} — {revenue} CHF across {count} projects.',
    recHourlyRate: 'Your avg. rate is {rate} CHF/h. Consider raising prices on simpler projects.',
    recWorstType: '{type} generates {rate} CHF/h — well below average. Review pricing or estimated time.',
    freeDaysLabel: 'days off',
  },
  de: {
    dashboard: 'Übersicht',
    analytics: 'Analyse',
    allianceFormTitle: 'Alliance Projekte',
    fassungFormTitle: 'Fassung Projekte',
    paveFormTitle: 'Pavé Projekte',
    userManagement: 'Team',
    dashboardTitle: 'Atelier Übersicht',
    dashboardSubtitle: 'Arbeitsablaufoptimierung und Finanztracking.',
    totalProjects: 'Gesamtprojekte',
    in_progress: 'In Bearbeitung',
    completed: 'Abgeschlossen',
    pending: 'Ausstehend',
    weeklyWorkload: 'Teamauslastung',
    completedRevenue: 'Umsatz',
    projectsInProgress: 'Aktive Projekte',
    loading: 'Laden...',
    noProjects: 'Keine Projekte in diesem Zeitraum.',
    createProject: 'Projekt erstellen',
    projectSaved: 'Projekt gespeichert!',
    allProjects: 'Alle Projekte',
    stoneSize: 'Steingröße (mm)',
    stoneType: 'Steinart',
    material: 'Material',
    style: 'Stil',
    shape: 'Form',
    timePerStone: 'Zeit/Stein (min)',
    totalTime: 'Gesch. Gesamtzeit',
    actualTime: 'Tatsächliche Zeit',
    pricePerStone: 'Preis/Stein (CHF)',
    goldBack: 'Gold zurück (g)',
    client: 'Kunde',
    date: 'Startdatum',
    deadline: 'Liefertermin',
    stoneCount: 'Anzahl Steine',
    layout: 'Layout',
    fixation: 'Fixierung',
    submit: 'Zum Zeitplan hinzufügen',
    extraHours: 'Extrastunden',
    addUser: 'Benutzer hinzufügen',
    newUser: 'Neuer Benutzername',
    status: 'Status',
    projectName: 'Projekt Name',
    revenue: 'Einnahmen',
    basedOnCompleted: 'Basierend auf Auswahl',
    filter_week: 'Woche',
    filter_month: 'Monat',
    filter_year: 'Jahr',
    filter_all: 'Gesamt',
    editProject: 'Projekt bearbeiten',
    agreedPrice: 'Vereinbarter Preis',
    priceAlert: 'Kosten übersteigen Schätzung',
    saveChanges: 'Änderungen speichern',
    proposalSimulation: 'Angebot Simulation',
    difficultyMargin: 'Schwierigkeitsmarge',
    urgencyFee: 'Dringlichkeitsgebühr',
    suggestedPrice: 'Vorgeschlagener Preis',
    suggestedDate: 'Optimierte Lieferung',
    calculate: 'Simulieren',
    assignedTo: 'Zugewiesen an',
    filterByUser: 'Nach Juwelier filtern',
    allUsers: 'Gesamtes Team',
    close: 'Schließen',
    previousMonth: 'Vorheriger Monat',
    nextMonth: 'Nächster Monat',
    startTimer: 'Timer starten',
    stopTimer: 'Timer stoppen',
    timerActive: 'Timer läuft',
    elapsedTime: 'Vergangen',
    estimatedCost: 'Gesch. Kosten',
    profitMargin: 'Marge',
    analyticsTitle: 'Analyse & Rentabilität',
    analyticsSubtitle: 'Finanzielle Leistung und Optimierungsempfehlungen.',
    revenueToday: 'Heute',
    revenueMonth: 'Diesen Monat',
    revenueYear: 'Dieses Jahr',
    revenueAllTime: 'Gesamt',
    profitabilityByType: 'Rentabilität nach Typ',
    topClients: 'Top Kunden',
    monthlyTrend: 'Monatlicher Umsatz',
    chfPerHour: 'CHF/Stunde',
    recommendations: 'Empfehlungen',
    projectCount: 'Projekte',
    avgPrice: 'Ø Preis',
    mostProfitable: 'Profitabelster Typ',
    bestClient: 'Bester Kunde',
    hourlyRate: 'Ø Stundensatz',
    workingDays: 'Arbeitstage',
    daysOff: 'Freie Tage',
    addDayOff: 'Freien Tag hinzufügen',
    mon: 'Mo', tue: 'Di', wed: 'Mi', thu: 'Do', fri: 'Fr', sat: 'Sa', sun: 'So',
    availability: 'Verfügbarkeit',
    smartPrediction: 'Intelligente Vorhersage',
    basedOnSimilar: 'Basierend auf {count} ähnlichen Projekten',
    predictedTime: 'Vorhergesagte Zeit',
    predictedPrice: 'Vorhergesagter Preis',
    timeRange: 'Bereich',
    goldPrice: 'Goldpreis',
    goldPriceLabel: 'Gold (CHF/g)',
    overdueToday: 'Überfällig/Heute',
    daysLabel: 'Tage',
    ofEstimated: 'von {est} gesch.',
    recBestType: '{type} ({rate} CHF/h). Priorisiere diesen Typ für maximalen Gewinn.',
    recBestClient: '{client} — {revenue} CHF in {count} Projekten.',
    recHourlyRate: 'Dein Ø-Stundensatz ist {rate} CHF/h. Erwäge, die Preise bei einfachen Projekten zu erhöhen.',
    recWorstType: '{type} erzeugt {rate} CHF/h — weit unter dem Durchschnitt. Preise oder Zeitschätzung überprüfen.',
    freeDaysLabel: 'freie Tage',
  },
  cat: {
    dashboard: 'Taulell',
    analytics: 'Analítiques',
    allianceFormTitle: 'Projectes Alliance',
    fassungFormTitle: 'Projectes Fassung',
    paveFormTitle: 'Projectes Pavé',
    userManagement: 'Equip',
    dashboardTitle: 'Resum del Taller',
    dashboardSubtitle: 'Optimització del flux de treball i seguiment financer.',
    totalProjects: 'Projectes Totals',
    in_progress: 'En curs',
    completed: 'Completat',
    pending: 'Pendent',
    weeklyWorkload: 'Càrrega de l\'Equip',
    completedRevenue: 'Facturació',
    projectsInProgress: 'Projectes Actius',
    loading: 'Carregant...',
    noProjects: 'Cap projecte en aquest període.',
    createProject: 'Crear Projecte',
    projectSaved: 'Projecte guardat!',
    allProjects: 'Tots els Projectes',
    stoneSize: 'Mida Pedra (mm)',
    stoneType: 'Tipus de Pedra',
    material: 'Material',
    style: 'Estil',
    shape: 'Forma',
    timePerStone: 'Temps/Pedra (min)',
    totalTime: 'Temps Estimat',
    actualTime: 'Temps Real',
    pricePerStone: 'Preu/Pedra (CHF)',
    goldBack: 'Or retornat (g)',
    client: 'Client',
    date: 'Data Inici',
    deadline: 'Data Entrega',
    stoneCount: 'Quantitat Pedres',
    layout: 'Disposició',
    fixation: 'Fixació',
    submit: 'Afegir al Calendari',
    extraHours: 'Hores extra',
    addUser: 'Afegir Usuari',
    newUser: 'Nom del nou usuari',
    status: 'Estat',
    projectName: 'Nom del Projecte',
    revenue: 'Ingressos',
    basedOnCompleted: 'Basat en la selecció',
    filter_week: 'Setmana',
    filter_month: 'Mes',
    filter_year: 'Any',
    filter_all: 'Tot',
    editProject: 'Editar Projecte',
    agreedPrice: 'Preu Acordat',
    priceAlert: 'El cost supera l\'estimació',
    saveChanges: 'Guardar Canvis',
    proposalSimulation: 'Simulació de Proposta',
    difficultyMargin: 'Marge de Dificultat',
    urgencyFee: 'Taxa d\'Urgència',
    suggestedPrice: 'Preu Suggerit',
    suggestedDate: 'Entrega Optimitzada',
    calculate: 'Simular',
    assignedTo: 'Assignat a',
    filterByUser: 'Filtrar per Joier',
    allUsers: 'Tot l\'Equip',
    close: 'Tancar',
    previousMonth: 'Mes Anterior',
    nextMonth: 'Mes Següent',
    startTimer: 'Iniciar Temporitzador',
    stopTimer: 'Aturar Temporitzador',
    timerActive: 'Temporitzador actiu',
    elapsedTime: 'Temps transcorregut',
    estimatedCost: 'Cost estimat',
    profitMargin: 'Marge',
    analyticsTitle: 'Analítiques i Rendibilitat',
    analyticsSubtitle: 'Rendiment financer i recomanacions d\'optimització.',
    revenueToday: 'Avui',
    revenueMonth: 'Aquest Mes',
    revenueYear: 'Aquest Any',
    revenueAllTime: 'Total Històric',
    profitabilityByType: 'Rendibilitat per Tipus',
    topClients: 'Millors Clients',
    monthlyTrend: 'Tendència Mensual',
    chfPerHour: 'CHF/hora',
    recommendations: 'Recomanacions',
    projectCount: 'Projectes',
    avgPrice: 'Preu Mitjà',
    mostProfitable: 'Tipus més rendible',
    bestClient: 'Millor client',
    hourlyRate: 'Tarifa horària mitjana',
    workingDays: 'Dies laborables',
    daysOff: 'Dies lliures',
    addDayOff: 'Afegir dia lliure',
    mon: 'Dl', tue: 'Dm', wed: 'Dc', thu: 'Dj', fri: 'Dv', sat: 'Ds', sun: 'Dg',
    availability: 'Disponibilitat',
    smartPrediction: 'Predicció Intel·ligent',
    basedOnSimilar: 'Basat en {count} projectes similars',
    predictedTime: 'Temps predit',
    predictedPrice: 'Preu predit',
    timeRange: 'Rang',
    goldPrice: 'Preu de l\'or',
    goldPriceLabel: 'Or (CHF/g)',
    overdueToday: 'Vençut/Avui',
    daysLabel: 'dies',
    ofEstimated: 'de {est} est.',
    recBestType: '{type} ({rate} CHF/h). Prioritza\'l per maximitzar beneficis.',
    recBestClient: '{client} — {revenue} CHF en {count} projectes.',
    recHourlyRate: 'La teva tarifa mitjana és {rate} CHF/h. Considera augmentar el preu acordat en projectes senzills.',
    recWorstType: '{type} genera {rate} CHF/h — molt per sota de la mitjana. Revisa els preus o el temps estimat.',
    freeDaysLabel: 'dies lliures',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('de');

  const t = (key: string, params?: Record<string, string | number>) => {
    let text = translations[language][key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v));
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useTranslation must be used within a LanguageProvider');
  return context;
};
